# Generated by Django 6.0.5 on 2026-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('boss_type', models.CharField(max_length=20)),
                ('reward_xp', models.IntegerField(default=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('monster_type', models.CharField(choices=[('goblin', 'Goblin'), ('troll', 'Troll'), ('dragon', 'Dragon')], max_length=20)),
                ('reward_xp', models.IntegerField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('char_class', models.CharField(choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('rogue', 'Rogue')], default='warrior', max_length=20)),
                ('rage', models.IntegerField(default=0)),
                ('victories', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
