# Generated by Django 6.0.5 on 2026-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='rage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='reward_gold',
            field=models.IntegerField(default=30),
        ),
    ]
