# Generated by Django 6.0.5 on 2026-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_monster_rage_monster_reward_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='atk_power',
            field=models.IntegerField(default=10),
        ),
    ]
