# Generated by Django 6.0.5 on 2026-05-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_monster_atk_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='reward_gold',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='reward_xp',
        ),
    ]
