# Generated by Django 6.0.5 on 2026-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_monster_reward_gold_remove_monster_reward_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='xp',
            field=models.IntegerField(default=50),
        ),
    ]
