# Generated by Django 6.0.5 on 2026-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_monster_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='image',
            field=models.CharField(default='/static/images/character.png', max_length=100),
        ),
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.CharField(default='/static/images/goblin.png', max_length=100),
        ),
        migrations.AddField(
            model_name='warrior',
            name='image',
            field=models.CharField(default='/static/images/warrior.png', max_length=100),
        ),
    ]
