# Generated by Django 6.0.5 on 2026-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_boss_image_monster_image_warrior_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='image',
            field=models.CharField(default='/static/images/Warrior.png', max_length=100),
        ),
    ]
