# Generated by Django 6.0.5 on 2026-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_warrior_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.CharField(default='/static/images/Goblin.png', max_length=100),
        ),
    ]
