# Generated by Django 6.0.5 on 2026-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_monster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='miss_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='miss_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warrior',
            name='miss_chance',
            field=models.IntegerField(default=0),
        ),
    ]
