# Generated by Django 6.0.5 on 2026-05-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_boss_miss_chance_monster_miss_chance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='miss_chance',
        ),
    ]
