# Generated by Django 6.0.5 on 2026-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_boss_miss_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='last_attack_missed',
            field=models.BooleanField(default=False),
        ),
    ]
