# Generated by Django 6.0.5 on 2026-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_warrior_last_attack_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='health',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.CharField(default='/static/images/Boss.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='boss',
            name='max_health',
            field=models.IntegerField(default=150),
        ),
    ]
