# Generated by Django 6.0.5 on 2026-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_boss_health_alter_boss_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='char_class',
            field=models.CharField(choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('rogue', 'Rogue'), ('ranger', 'Ranger'), ('warlock', 'Warlock')], default='warrior', max_length=20),
        ),
    ]
