# Generated by Django 6.0.5 on 2026-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_warrior_char_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='defeats',
            field=models.IntegerField(default=0),
        ),
    ]
