# Generated by Django 6.0.5 on 2026-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_warrior_defeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='boss_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
