# Generated by Django 6.0.5 on 2026-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_monster_boss_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
