# Generated by Django 6.0.5 on 2026-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_boss_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
