# Generated by Django 6.0.5 on 2026-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_boss_boss_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
