# Generated by Django 6.0.5 on 2026-06-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_warrior_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
