# Generated by Django 6.0.5 on 2026-06-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_boss_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='warrior',
            name='experience',
        ),
    ]
