# Generated by Django 6.0.5 on 2026-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_boss_experience_remove_warrior_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='attack_power',
            field=models.IntegerField(default=15),
        ),
    ]
