# Generated by Django 6.0.5 on 2026-06-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_boss_attack_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.CharField(default='/game/static', max_length=100),
        ),
    ]
