# Generated by Django 6.0.5 on 2026-06-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_boss_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
