# Generated by Django 6.0.5 on 2026-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_warrior_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
