# Generated by Django 6.1 on 2026-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_warrior_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='image',
            field=models.CharField(default='/static/images/warrior.svg', max_length=100),
        ),
    ]
