# Generated by Django 6.1 on 2026-08-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_warrior_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.CharField(default='/static/images/goblin_brute.svg', max_length=100),
        ),
    ]
