# Generated by Django 6.1 on 2026-08-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(choices=[('goblin', 'goblin'), ('troll', 'Troll'), ('dragon', 'Dragon')], max_length=20),
        ),
    ]
