# Generated by Django 6.1 on 2026-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_monster_monster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(choices=[('goblin', 'goblin'), ('troll', 'troll'), ('dragon', 'dragon')], max_length=20),
        ),
    ]
