# Generated by Django 6.1 on 2026-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_alter_monster_monster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='isdead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='image',
            field=models.CharField(default='/static/images/Warrior.svg', max_length=100),
        ),
    ]
