# Generated by Django 6.1 on 2026-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_warrior_isdead_alter_warrior_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.CharField(default='/game/static/images', max_length=100),
        ),
    ]
