# Generated by Django 6.1 on 2026-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_alter_boss_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleniumTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtest', models.IntegerField(default=0)),
                ('test_name', models.CharField(max_length=20)),
                ('test_description', models.TextField()),
            ],
        ),
    ]
