# Generated by Django 6.1 on 2026-08-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_seleniumtests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seleniumtests',
            options={'permissions': [('run_selenium_tests', 'Can run Selenium tests')]},
        ),
    ]
