# Generated by Django 6.1 on 2026-08-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_alter_seleniumtests_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seleniumtests',
            options={'permissions': [('seleniumtests', 'Can run Selenium tests')]},
        ),
    ]
