# Generated by Django 6.1 on 2026-08-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_alter_seleniumtests_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seleniumtests',
            options={'permissions': [('game.view_seleniumtests', 'Can run Selenium tests')]},
        ),
    ]
